{
 "title": "Spring AI v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Token Usage Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Tokens/sec" } },
   "targets": [
    {
     "expr": "sum by(gen_ai_operation_name, gen_ai_system) (rate(gen_ai_client_token_usage_total{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{gen_ai_system}}-{{gen_ai_operation_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Error counts/rate for the AI model requests",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gen_ai_client_operation_seconds_count{application=\"$application\", error!=\"none\"}",
     "legendFormat": "{{gen_ai_operation_name}}-{{error}}"
    },
    {
     "expr": "db_vector_client_operation_seconds_count{application=\"$application\", error!=\"none\"}",
     "legendFormat": "{{db_system}}-{{error}}}}"
    }
   ]
  },
  {
   "title": "Top Models",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(gen_ai_operation_name, gen_ai_system, gen_ai_request_model) (increase(gen_ai_client_operation_seconds_count{application=\"$application\", error=\"none\"}[$__rate_interval])))",
     "legendFormat": "{{gen_ai_operation_name}} ({{gen_ai_system}}/{{gen_ai_request_model}})"
    }
   ]
  },
  {
   "title": "Models Success vs Errors",
   "type": "piechart",
   "description": "Error counts/rate for the AI model requests",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(gen_ai_operation_name, error) (gen_ai_client_operation_seconds_count{application=\"$application\"})",
     "legendFormat": "{{gen_ai_operation_name}}-{{error}}"
    }
   ]
  },
  {
   "title": "Top Vector DBs",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(db_system, db_operation_name) (increase(db_vector_client_operation_seconds_count{application=\"$application\", error=\"none\"}[$__rate_interval])))",
     "legendFormat": "{{db_system}} ({{db_operation_name}})"
    }
   ]
  },
  {
   "title": "Top Tools",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(gen_ai_operation_name, gen_ai_system, spring_ai_tool_definition_name) (increase(spring_ai_tool_seconds_count{application=\"$application\", error=\"none\"}[$__rate_interval])))",
     "legendFormat": "{{spring_ai_tool_definition_name}} "
    }
   ]
  },
  {
   "title": "Models Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(gen_ai_operation_name, error, gen_ai_system, gen_ai_request_model) (rate(gen_ai_client_operation_seconds_count{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{gen_ai_operation_name}} ({{gen_ai_system}}/{{gen_ai_request_model}}) - {{error}}"
    }
   ]
  },
  {
   "title": "Models Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(error, gen_ai_operation_name, gen_ai_system, gen_ai_request_model) (gen_ai_client_operation_seconds_bucket{application=\"$application\"})",
     "legendFormat": "Max - {{gen_ai_operation_name}} ({{gen_ai_system}}/{{gen_ai_request_model}}) - {{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, gen_ai_operation_name, gen_ai_request_model, error, gen_ai_system) (rate(gen_ai_client_operation_seconds_bucket{application=\"$application\"}[$__rate_interval])))",
     "legendFormat": "Tp99 - {{gen_ai_operation_name}} ({{gen_ai_system}}/{{gen_ai_request_model}}) - {{error}}"
    }
   ]
  },
  {
   "title": "Vector DB Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(db_system, db_operation_name, error) (rate(db_vector_client_operation_seconds_count{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{db_system}}-{{db_operation_name}}-{{error}}"
    }
   ]
  },
  {
   "title": "Vector DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(db_operation_name, error, db_system) (db_vector_client_operation_seconds_max{application=\"$application\"})",
     "legendFormat": "Max {{db_system}} ({{db_operation_name}}) - {{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, error, db_system, db_operation_name) (rate(db_vector_client_operation_seconds_bucket{application=\"$application\"}[$__rate_interval])))",
     "legendFormat": "Tp99 {{db_system}} ({{db_operation_name}}) - {{error}}"
    }
   ]
  },
  {
   "title": "Search Traces $application",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "filters": [
      { "id": "df333216", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$application" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "{application=\"$application\", level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "Chat Client Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(error, spring_ai_chat_client_stream) (rate(spring_ai_chat_client_seconds_count{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "Stream: {{spring_ai_chat_client_stream}} - {{error}}"
    }
   ]
  },
  {
   "title": "Chat Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(error, spring_ai_chat_client_stream) (spring_ai_chat_client_seconds_max{application=\"$application\"})",
     "legendFormat": "Max stream: {{spring_ai_chat_client_stream}} - {{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, error, spring_ai_chat_client_stream) (rate(spring_ai_chat_client_seconds_bucket{application=\"$application\"}[$__rate_interval])))",
     "legendFormat": "Tp99 stream: {{spring_ai_chat_client_stream}} - {{error}}"
    }
   ]
  },
  {
   "title": "Tools Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(gen_ai_operation_name, error, gen_ai_system, spring_ai_tool_definition_name) (rate(spring_ai_tool_seconds_count{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{spring_ai_tool_definition_name}}({{gen_ai_operation_name}}/{{gen_ai_system}}) - {{error}}"
    }
   ]
  },
  {
   "title": "Tools Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(error, gen_ai_operation_name, gen_ai_system, spring_ai_tool_definition_name) (spring_ai_tool_seconds_bucket{application=\"$application\"})",
     "legendFormat": "Max - {{spring_ai_tool_definition_name}}({{gen_ai_operation_name}}/{{gen_ai_system}}) - {{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, gen_ai_operation_name, spring_ai_tool_definition_name, error, gen_ai_system) (rate(spring_ai_tool_seconds_bucket{application=\"$application\"}[$__rate_interval])))",
     "legendFormat": "Tp99 - {{spring_ai_tool_definition_name}}({{gen_ai_operation_name}}/{{gen_ai_system}}) - {{error}}"
    }
   ]
  }
 ]
}